defmodule Craftplan.Repo.TenantMigrations.AddMultitenancyTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orders_production_batches, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :batch_code, :text, null: false
      add :planned_qty, :decimal, null: false, default: "0"
      add :produced_qty, :decimal, null: false, default: "0"
      add :scrap_qty, :decimal, null: false, default: "0"
      add :status, :text, null: false, default: "open"
      add :notes, :text
      add :bom_version, :bigint
      add :components_map, :map, null: false, default: %{}
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :product_id, :uuid, null: false
      add :bom_id, :uuid
    end

    create index(:orders_production_batches, [:batch_code],
             name: "orders_production_batches_batch_code_index",
             unique: true
           )

    create table(:orders_production_batch_lots, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity_used, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :production_batch_id,
          references(:orders_production_batches,
            column: :id,
            name: "orders_production_batch_lots_production_batch_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :lot_id, :uuid, null: false
    end

    create index(:orders_production_batch_lots, [:lot_id], name: "orders_production_batch_lots_lot_idx")

    create index(:orders_production_batch_lots, [:production_batch_id], name: "orders_production_batch_lots_batch_idx")

    create table(:orders_orders, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :currency, :text, null: false, default: "USD"
      add :reference, :text, null: false
      add :delivery_date, :utc_datetime, null: false
      add :invoice_number, :text
      add :invoice_status, :text, null: false, default: "none"
      add :invoiced_at, :utc_datetime
      add :payment_method, :text
      add :discount_type, :text, null: false, default: "none"
      add :discount_value, :decimal, null: false, default: "0"
      add :delivery_method, :text, null: false, default: "delivery"
      add :status, :text, null: false, default: "unconfirmed"
      add :payment_status, :text, null: false, default: "pending"
      add :subtotal, :decimal, null: false, default: "0"
      add :tax_total, :decimal, null: false, default: "0"
      add :shipping_total, :decimal, null: false, default: "0"
      add :discount_total, :decimal, null: false, default: "0"
      add :total, :decimal, null: false, default: "0"
      add :paid_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id, :uuid, null: false
    end

    create table(:orders_items, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :unit_price, :decimal, null: false
      add :quantity, :decimal, null: false
      add :status, :text, null: false, default: "todo"
      add :consumed_at, :utc_datetime
      add :batch_code, :text
      add :material_cost, :decimal, null: false, default: "0"
      add :labor_cost, :decimal, null: false, default: "0"
      add :overhead_cost, :decimal, null: false, default: "0"
      add :unit_cost, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:orders_orders,
            column: :id,
            name: "orders_items_order_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :product_id, :uuid, null: false
      add :bom_id, :uuid
      add :production_batch_id, :uuid
    end

    create table(:orders_item_lots, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity_used, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_item_id,
          references(:orders_items,
            column: :id,
            name: "orders_item_lots_order_item_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :lot_id, :uuid, null: false
    end

    create table(:orders_item_batch_allocations, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :planned_qty, :decimal, null: false, default: "0"
      add :completed_qty, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :production_batch_id,
          references(:orders_production_batches,
            column: :id,
            name: "orders_item_batch_allocations_production_batch_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :order_item_id,
          references(:orders_items,
            column: :id,
            name: "orders_item_batch_allocations_order_item_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create index(:orders_item_batch_allocations, [:production_batch_id], name: "orders_item_batch_allocations_batch_idx")

    create index(:orders_item_batch_allocations, [:order_item_id], name: "orders_item_batch_allocations_item_idx")

    create index(:orders_item_batch_allocations, [:production_batch_id, :order_item_id],
             name: "orders_item_batch_allocations_unique_pair",
             unique: true
           )

    create table(:inventory_suppliers, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :contact_name, :text
      add :contact_email, :text
      add :contact_phone, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:inventory_purchase_orders, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :reference, :text, null: false
      add :status, :text, null: false, default: "draft"
      add :ordered_at, :utc_datetime
      add :received_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :supplier_id,
          references(:inventory_suppliers,
            column: :id,
            name: "inventory_purchase_orders_supplier_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create unique_index(:inventory_purchase_orders, [:reference], name: "inventory_purchase_orders_reference_index")

    create table(:inventory_purchase_order_items, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false, default: "0"
      add :unit_price, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :purchase_order_id,
          references(:inventory_purchase_orders,
            column: :id,
            name: "inventory_purchase_order_items_purchase_order_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "inventory_purchase_order_items_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:inventory_movements, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false
      add :reason, :text
      add :occurred_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "inventory_movements_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :lot_id, :uuid
    end

    create table(:inventory_lots, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders_production_batch_lots, prefix: prefix()) do
      modify :lot_id,
             references(:inventory_lots,
               column: :id,
               name: "orders_production_batch_lots_lot_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:orders_item_lots, prefix: prefix()) do
      modify :lot_id,
             references(:inventory_lots,
               column: :id,
               name: "orders_item_lots_lot_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:inventory_movements, prefix: prefix()) do
      modify :lot_id,
             references(:inventory_lots,
               column: :id,
               name: "inventory_movements_lot_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:inventory_lots, prefix: prefix()) do
      add :lot_code, :text, null: false
      add :expiry_date, :date
      add :received_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "inventory_lots_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :supplier_id,
          references(:inventory_suppliers,
            column: :id,
            name: "inventory_lots_supplier_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create index(:inventory_lots, [:supplier_id], name: "inventory_lots_supplier_id_index")

    create index(:inventory_lots, [:material_id], name: "inventory_lots_material_id_index")

    create index(:inventory_lots, [:lot_code],
             name: "inventory_lots_lot_code_index",
             unique: true
           )

    create table(:crm_customers, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders_orders, prefix: prefix()) do
      modify :customer_id,
             references(:crm_customers,
               column: :id,
               name: "orders_orders_customer_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    create unique_index(:orders_orders, [:reference], name: "orders_orders_reference_index")

    alter table(:crm_customers, prefix: prefix()) do
      add :reference, :text, null: false
      add :type, :text, null: false
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :email, :text
      add :phone, :text
      add :billing_address, :map
      add :shipping_address, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:crm_customers, [:email], name: "crm_customers_email_index")

    create unique_index(:crm_customers, [:phone], name: "crm_customers_phone_index")

    create unique_index(:crm_customers, [:reference], name: "crm_customers_reference_index")

    create table(:catalog_products, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders_production_batches, prefix: prefix()) do
      modify :product_id,
             references(:catalog_products,
               column: :id,
               name: "orders_production_batches_product_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:orders_items, prefix: prefix()) do
      modify :product_id,
             references(:catalog_products,
               column: :id,
               name: "orders_items_product_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:catalog_products, prefix: prefix()) do
      add :name, :text, null: false
      add :status, :text, null: false, default: "draft"
      add :price, :decimal, null: false
      add :sku, :text, null: false
      add :photos, {:array, :text}, default: []
      add :featured_photo, :text
      add :selling_availability, :text, null: false, default: "available"
      add :max_daily_quantity, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:catalog_products, [:name], name: "catalog_products_name_index")

    create unique_index(:catalog_products, [:sku], name: "catalog_products_sku_index")

    create table(:catalog_labor_steps, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :sequence, :bigint, null: false, default: 0
      add :duration_minutes, :decimal, null: false, default: "0"
      add :rate_override, :decimal
      add :units_per_run, :decimal, null: false, default: "1"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bom_id, :uuid, null: false
    end

    create table(:catalog_boms, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders_production_batches, prefix: prefix()) do
      modify :bom_id,
             references(:catalog_boms,
               column: :id,
               name: "orders_production_batches_bom_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:orders_items, prefix: prefix()) do
      modify :bom_id,
             references(:catalog_boms,
               column: :id,
               name: "orders_items_bom_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :production_batch_id,
             references(:orders_production_batches,
               column: :id,
               name: "orders_items_production_batch_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:catalog_labor_steps, prefix: prefix()) do
      modify :bom_id,
             references(:catalog_boms,
               column: :id,
               name: "catalog_labor_steps_bom_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:catalog_boms, prefix: prefix()) do
      add :name, :text
      add :notes, :text
      add :status, :text, null: false, default: "draft"
      add :version, :bigint, null: false
      add :published_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :product_id,
          references(:catalog_products,
            column: :id,
            name: "catalog_boms_product_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create index(:catalog_boms, [:product_id],
             name: "catalog_boms_one_active_per_product",
             unique: true,
             where: "status = 'active'"
           )

    create unique_index(:catalog_boms, [:product_id, :version], name: "catalog_boms_product_version_index")

    create table(:catalog_bom_rollups, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :material_cost, :decimal, null: false, default: "0"
      add :labor_cost, :decimal, null: false, default: "0"
      add :overhead_cost, :decimal, null: false, default: "0"
      add :unit_cost, :decimal, null: false, default: "0"
      add :components_map, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bom_id,
          references(:catalog_boms,
            column: :id,
            name: "catalog_bom_rollups_bom_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :product_id,
          references(:catalog_products,
            column: :id,
            name: "catalog_bom_rollups_product_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create unique_index(:catalog_bom_rollups, [:bom_id], name: "catalog_bom_rollups_unique_bom_index")

    create table(:catalog_bom_components, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :component_type, :text, null: false, default: "material"
      add :quantity, :decimal, null: false, default: "0"
      add :position, :bigint, null: false, default: 0
      add :waste_percent, :decimal, null: false, default: "0"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bom_id,
          references(:catalog_boms,
            column: :id,
            name: "catalog_bom_components_bom_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "catalog_bom_components_material_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :product_id,
          references(:catalog_products,
            column: :id,
            name: "catalog_bom_components_product_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end
  end

  def down do
    drop constraint(:catalog_bom_components, "catalog_bom_components_bom_id_fkey")

    drop constraint(:catalog_bom_components, "catalog_bom_components_material_id_fkey")

    drop constraint(:catalog_bom_components, "catalog_bom_components_product_id_fkey")

    drop table(:catalog_bom_components, prefix: prefix())

    drop_if_exists unique_index(:catalog_bom_rollups, [:bom_id], name: "catalog_bom_rollups_unique_bom_index")

    drop constraint(:catalog_bom_rollups, "catalog_bom_rollups_bom_id_fkey")

    drop constraint(:catalog_bom_rollups, "catalog_bom_rollups_product_id_fkey")

    drop table(:catalog_bom_rollups, prefix: prefix())

    drop_if_exists unique_index(:catalog_boms, [:product_id, :version], name: "catalog_boms_product_version_index")

    drop constraint(:catalog_boms, "catalog_boms_product_id_fkey")

    drop_if_exists index(:catalog_boms, [:product_id], name: "catalog_boms_one_active_per_product")

    alter table(:catalog_boms, prefix: prefix()) do
      remove :product_id
      remove :updated_at
      remove :inserted_at
      remove :published_at
      remove :version
      remove :status
      remove :notes
      remove :name
    end

    drop constraint(:catalog_labor_steps, "catalog_labor_steps_bom_id_fkey")

    alter table(:catalog_labor_steps, prefix: prefix()) do
      modify :bom_id, :uuid
    end

    drop constraint(:orders_items, "orders_items_bom_id_fkey")

    drop constraint(:orders_items, "orders_items_production_batch_id_fkey")

    alter table(:orders_items, prefix: prefix()) do
      modify :production_batch_id, :uuid
      modify :bom_id, :uuid
    end

    drop constraint(:orders_production_batches, "orders_production_batches_bom_id_fkey")

    alter table(:orders_production_batches, prefix: prefix()) do
      modify :bom_id, :uuid
    end

    drop table(:catalog_boms, prefix: prefix())

    drop table(:catalog_labor_steps, prefix: prefix())

    drop_if_exists unique_index(:catalog_products, [:sku], name: "catalog_products_sku_index")

    drop_if_exists unique_index(:catalog_products, [:name], name: "catalog_products_name_index")

    alter table(:catalog_products, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :max_daily_quantity
      remove :selling_availability
      remove :featured_photo
      remove :photos
      remove :sku
      remove :price
      remove :status
      remove :name
    end

    drop constraint(:orders_items, "orders_items_product_id_fkey")

    alter table(:orders_items, prefix: prefix()) do
      modify :product_id, :uuid
    end

    drop constraint(:orders_production_batches, "orders_production_batches_product_id_fkey")

    alter table(:orders_production_batches, prefix: prefix()) do
      modify :product_id, :uuid
    end

    drop table(:catalog_products, prefix: prefix())

    drop_if_exists unique_index(:crm_customers, [:reference], name: "crm_customers_reference_index")

    drop_if_exists unique_index(:crm_customers, [:phone], name: "crm_customers_phone_index")

    drop_if_exists unique_index(:crm_customers, [:email], name: "crm_customers_email_index")

    alter table(:crm_customers, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :shipping_address
      remove :billing_address
      remove :phone
      remove :email
      remove :last_name
      remove :first_name
      remove :type
      remove :reference
    end

    drop_if_exists unique_index(:orders_orders, [:reference], name: "orders_orders_reference_index")

    drop constraint(:orders_orders, "orders_orders_customer_id_fkey")

    alter table(:orders_orders, prefix: prefix()) do
      modify :customer_id, :uuid
    end

    drop table(:crm_customers, prefix: prefix())

    drop constraint(:inventory_lots, "inventory_lots_material_id_fkey")

    drop constraint(:inventory_lots, "inventory_lots_supplier_id_fkey")

    drop_if_exists index(:inventory_lots, [:lot_code], name: "inventory_lots_lot_code_index")

    drop_if_exists index(:inventory_lots, [:material_id], name: "inventory_lots_material_id_index")

    drop_if_exists index(:inventory_lots, [:supplier_id], name: "inventory_lots_supplier_id_index")

    alter table(:inventory_lots, prefix: prefix()) do
      remove :supplier_id
      remove :material_id
      remove :updated_at
      remove :inserted_at
      remove :received_at
      remove :expiry_date
      remove :lot_code
    end

    drop constraint(:inventory_movements, "inventory_movements_lot_id_fkey")

    alter table(:inventory_movements, prefix: prefix()) do
      modify :lot_id, :uuid
    end

    drop constraint(:orders_item_lots, "orders_item_lots_lot_id_fkey")

    alter table(:orders_item_lots, prefix: prefix()) do
      modify :lot_id, :uuid
    end

    drop constraint(:orders_production_batch_lots, "orders_production_batch_lots_lot_id_fkey")

    alter table(:orders_production_batch_lots, prefix: prefix()) do
      modify :lot_id, :uuid
    end

    drop table(:inventory_lots, prefix: prefix())

    drop constraint(:inventory_movements, "inventory_movements_material_id_fkey")

    drop table(:inventory_movements, prefix: prefix())

    drop constraint(
           :inventory_purchase_order_items,
           "inventory_purchase_order_items_purchase_order_id_fkey"
         )

    drop constraint(
           :inventory_purchase_order_items,
           "inventory_purchase_order_items_material_id_fkey"
         )

    drop table(:inventory_purchase_order_items, prefix: prefix())

    drop_if_exists unique_index(:inventory_purchase_orders, [:reference],
                     name: "inventory_purchase_orders_reference_index"
                   )

    drop constraint(:inventory_purchase_orders, "inventory_purchase_orders_supplier_id_fkey")

    drop table(:inventory_purchase_orders, prefix: prefix())

    drop table(:inventory_suppliers, prefix: prefix())

    drop constraint(
           :orders_item_batch_allocations,
           "orders_item_batch_allocations_production_batch_id_fkey"
         )

    drop constraint(
           :orders_item_batch_allocations,
           "orders_item_batch_allocations_order_item_id_fkey"
         )

    drop_if_exists index(:orders_item_batch_allocations, [:production_batch_id, :order_item_id],
                     name: "orders_item_batch_allocations_unique_pair"
                   )

    drop_if_exists index(:orders_item_batch_allocations, [:order_item_id], name: "orders_item_batch_allocations_item_idx")

    drop_if_exists index(:orders_item_batch_allocations, [:production_batch_id],
                     name: "orders_item_batch_allocations_batch_idx"
                   )

    drop table(:orders_item_batch_allocations, prefix: prefix())

    drop constraint(:orders_item_lots, "orders_item_lots_order_item_id_fkey")

    drop table(:orders_item_lots, prefix: prefix())

    drop constraint(:orders_items, "orders_items_order_id_fkey")

    drop table(:orders_items, prefix: prefix())

    drop table(:orders_orders, prefix: prefix())

    drop constraint(
           :orders_production_batch_lots,
           "orders_production_batch_lots_production_batch_id_fkey"
         )

    drop_if_exists index(:orders_production_batch_lots, [:production_batch_id],
                     name: "orders_production_batch_lots_batch_idx"
                   )

    drop_if_exists index(:orders_production_batch_lots, [:lot_id], name: "orders_production_batch_lots_lot_idx")

    drop table(:orders_production_batch_lots, prefix: prefix())

    drop_if_exists index(:orders_production_batches, [:batch_code], name: "orders_production_batches_batch_code_index")

    drop table(:orders_production_batches, prefix: prefix())
  end
end
