defmodule Craftplan.Repo.Migrations.UpdateMultitenancyTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :name, :text, null: false
      add :active, :boolean, null: false
      add :plan, :text, null: false
    end

    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, default: "member"

      add :joined, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :user_id,
          references(:accounts_users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:memberships, [:organization_id, :user_id],
             name: "memberships_unique_membership_index"
           )

    drop constraint(:accounts_users, "accounts_users_organization_id_fkey")

    alter table(:accounts_users) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "accounts_users_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:accounts_users, [:email],
                     name: "accounts_users_unique_email_index"
                   )

    create unique_index(:accounts_users, [:email], name: "accounts_users_unique_email_index")

    drop constraint(:accounts_api_keys, "accounts_api_keys_user_id_fkey")

    alter table(:accounts_api_keys) do
      modify :user_id,
             references(:accounts_users,
               column: :id,
               name: "accounts_api_keys_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:accounts_api_keys, "accounts_api_keys_user_id_fkey")

    alter table(:accounts_api_keys) do
      modify :user_id,
             references(:accounts_users,
               column: :id,
               name: "accounts_api_keys_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:accounts_users, [:email],
                     name: "accounts_users_unique_email_index"
                   )

    create unique_index(:accounts_users, [:email], name: "accounts_users_unique_email_index")

    drop constraint(:accounts_users, "accounts_users_organization_id_fkey")

    alter table(:accounts_users) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "accounts_users_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:memberships, [:organization_id, :user_id],
                     name: "memberships_unique_membership_index"
                   )

    drop constraint(:memberships, "memberships_organization_id_fkey")

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop table(:memberships)

    drop constraint(:organizations, "organizations_owner_id_fkey")

    alter table(:organizations) do
      remove :owner_id
      remove :plan
      remove :active
      remove :name
    end
  end
end
