defmodule Craftplan.Repo.Migrations.AddMultitenancyTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :slug, :text, null: false
    end

    alter table(:accounts_users) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "accounts_users_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    alter table(:accounts_users) do
      remove :organizations_id
    end

    drop table(:organizations)
  end
end
