defmodule Craftplan.Repo.Migrations.AddObanTriggers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:settings) do
      modify :labor_hourly_rate, :money_with_currency, null: true, default: fragment("('EUR', 0)")
      modify :shipping_flat, :money_with_currency, null: true, default: fragment("('EUR', 0)")
      modify :currency, :text, default: "EUR"
    end

    alter table(:orders_orders) do
      remove :currency
      modify :total, :money_with_currency, default: fragment("('EUR', 0)")
      modify :discount_total, :money_with_currency, default: fragment("('EUR', 0)")
      modify :shipping_total, :money_with_currency, default: fragment("('EUR', 0)")
      modify :tax_total, :money_with_currency, default: fragment("('EUR', 0)")
      modify :subtotal, :money_with_currency, default: fragment("('EUR', 0)")
    end

    alter table(:orders_items) do
      modify :unit_cost, :money_with_currency, default: fragment("('EUR', 0)")
      modify :overhead_cost, :money_with_currency, default: fragment("('EUR', 0)")
      modify :labor_cost, :money_with_currency, default: fragment("('EUR', 0)")
      modify :material_cost, :money_with_currency, default: fragment("('EUR', 0)")
      modify :unit_price, :money_with_currency
    end

    alter table(:inventory_purchase_order_items) do
      modify :unit_price, :money_with_currency
    end

    alter table(:inventory_materials) do
      modify :price, :money_with_currency
    end

    alter table(:catalog_products) do
      modify :price, :money_with_currency
    end

    alter table(:catalog_labor_steps) do
      modify :rate_override, :money_with_currency
    end

    alter table(:catalog_bom_rollups) do
      modify :unit_cost, :money_with_currency, default: fragment("('EUR', 0)")
      modify :overhead_cost, :money_with_currency, default: fragment("('EUR', 0)")
      modify :labor_cost, :money_with_currency, default: fragment("('EUR', 0)")
      modify :material_cost, :money_with_currency, default: fragment("('EUR', 0)")
    end
  end

  def down do
    alter table(:catalog_bom_rollups) do
      modify :material_cost, :decimal, default: "0"
      modify :labor_cost, :decimal, default: "0"
      modify :overhead_cost, :decimal, default: "0"
      modify :unit_cost, :decimal, default: "0"
    end

    alter table(:catalog_labor_steps) do
      modify :rate_override, :decimal
    end

    alter table(:catalog_products) do
      modify :price, :decimal
    end

    alter table(:inventory_materials) do
      modify :price, :decimal
    end

    alter table(:inventory_purchase_order_items) do
      modify :unit_price, :decimal
    end

    alter table(:orders_items) do
      modify :unit_price, :decimal
      modify :material_cost, :decimal, default: "0"
      modify :labor_cost, :decimal, default: "0"
      modify :overhead_cost, :decimal, default: "0"
      modify :unit_cost, :decimal, default: "0"
    end

    alter table(:orders_orders) do
      modify :subtotal, :decimal, default: "0"
      modify :tax_total, :decimal, default: "0"
      modify :shipping_total, :decimal, default: "0"
      modify :discount_total, :decimal, default: "0"
      modify :total, :decimal, default: "0"
      add :currency, :text, null: false, default: "USD"
    end

    alter table(:settings) do
      remove :forecast_default_horizon_days
      remove :forecast_default_service_level
      remove :forecast_min_samples
      remove :forecast_planned_weight
      remove :forecast_actual_weight
      remove :forecast_lookback_days
      modify :currency, :text, default: "USD"
      modify :shipping_flat, :decimal, null: false, default: "0"
      modify :labor_hourly_rate, :decimal, null: false, default: "0"
    end
  end
end
