defmodule Craftplan.Repo.Migrations.UpdateMultitenancyTables3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:organizations, "organizations_owner_id_fkey")

    alter table(:organizations) do
      modify :owner_id,
             references(:accounts_users,
               column: :id,
               name: "organizations_owner_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    alter table(:accounts_api_keys) do
      modify :user_id,
             references(:accounts_users,
               column: :id,
               name: "accounts_api_keys_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:memberships) do
      modify :user_id,
             references(:accounts_users,
               column: :id,
               name: "memberships_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organizations) do
      modify :owner_id,
             references(:accounts_users,
               column: :id,
               name: "organizations_owner_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
