defmodule Craftplan.Repo.Migrations.UpdateMultitenancyTables2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:settings, "settings_organization_id_fkey")

    alter table(:settings) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "settings_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organizations) do
      add :owner_id,
          references(:accounts_users,
            column: :id,
            name: "organizations_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop constraint(:memberships, "memberships_organization_id_fkey")

    alter table(:memberships) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "memberships_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:accounts_users, "accounts_users_organization_id_fkey")

    alter table(:accounts_users) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "accounts_users_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:accounts_users, "accounts_users_organization_id_fkey")

    alter table(:accounts_users) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "accounts_users_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:memberships, "memberships_organization_id_fkey")

    alter table(:memberships) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "memberships_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:organizations, "organizations_owner_id_fkey")

    alter table(:organizations) do
      remove :slug
      remove :owner_id
      remove :plan
      remove :active
      remove :name
    end

    drop constraint(:settings, "settings_organization_id_fkey")

    alter table(:settings) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "settings_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop table(:organizations)
  end
end
