defmodule Craftplan.Repo.Migrations.Init do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :currency, :text, null: false, default: "USD"
      add :tax_mode, :text, null: false, default: "exclusive"
      add :tax_rate, :decimal, null: false, default: "0"
      add :offers_pickup, :boolean, null: false, default: true
      add :offers_delivery, :boolean, null: false, default: true
      add :lead_time_days, :bigint, null: false, default: 0
      add :daily_capacity, :bigint, null: false, default: 0
      add :shipping_flat, :decimal, null: false, default: "0"
      add :labor_hourly_rate, :decimal, null: false, default: "0"
      add :labor_overhead_percent, :decimal, null: false, default: "0"
      add :retail_markup_mode, :text, null: false, default: "percent"
      add :retail_markup_value, :decimal, null: false, default: "0"
      add :wholesale_markup_mode, :text, null: false, default: "percent"
      add :wholesale_markup_value, :decimal, null: false, default: "0"
      add :email_from_name, :text, null: false, default: "Craftplan"
      add :email_from_address, :text, null: false, default: "noreply@craftplan.app"
      add :email_provider, :text, null: false, default: "smtp"
      add :email_api_key, :binary
      add :email_api_secret, :binary
      add :email_api_domain, :text
      add :email_api_region, :text, default: "us-east-1"
      add :smtp_host, :text
      add :smtp_port, :bigint, default: 587
      add :smtp_username, :text
      add :smtp_password, :text
      add :smtp_tls, :text, default: "if_available"
      add :forecast_lookback_days, :bigint, null: false, default: 42
      add :forecast_actual_weight, :decimal, null: false, default: "0.6"
      add :forecast_planned_weight, :decimal, null: false, default: "0.4"
      add :forecast_min_samples, :bigint, null: false, default: 10
      add :forecast_default_service_level, :decimal, null: false, default: "0.95"
      add :forecast_default_horizon_days, :bigint, null: false, default: 14
      add :organization_id, :uuid
    end

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:settings) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "settings_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organizations) do
      add :name, :text, null: false
      add :active, :boolean, default: false
      add :plan, :text, default: "free"
      add :owner_id, :uuid
      add :prefix, :text, null: false
    end

    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, default: "member"

      add :joined, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :user_id, :uuid
    end

    create table(:inventory_nutritional_facts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:inventory_nutritional_facts, [:name],
             name: "inventory_nutritional_facts_name_index"
           )

    create table(:inventory_materials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :sku, :text, null: false
      add :unit, :text, null: false
      add :price, :decimal, null: false
      add :minimum_stock, :decimal
      add :maximum_stock, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:inventory_materials, [:name], name: "inventory_materials_name_index")

    create unique_index(:inventory_materials, [:sku], name: "inventory_materials_sku_index")

    create table(:inventory_material_nutritional_fact, primary_key: false) do
      add :amount, :decimal, null: false
      add :unit, :text, null: false

      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "inventory_material_nutritional_fact_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false

      add :nutritional_fact_id,
          references(:inventory_nutritional_facts,
            column: :id,
            name: "inventory_material_nutritional_fact_nutritional_fact_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false
    end

    create table(:inventory_material_allergen, primary_key: false) do
      add :material_id,
          references(:inventory_materials,
            column: :id,
            name: "inventory_material_allergen_material_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false

      add :allergen_id, :uuid, null: false, primary_key: true
    end

    create table(:inventory_allergens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:inventory_material_allergen) do
      modify :allergen_id,
             references(:inventory_allergens,
               column: :id,
               name: "inventory_material_allergen_allergen_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_allergens) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:inventory_allergens, [:name], name: "inventory_allergens_name_index")

    create table(:accounts_users, primary_key: false) do
      add :confirmed_at, :utc_datetime_usec
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:organizations) do
      modify :owner_id,
             references(:accounts_users,
               column: :id,
               name: "organizations_owner_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:memberships) do
      modify :user_id,
             references(:accounts_users,
               column: :id,
               name: "memberships_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:memberships, [:organization_id, :user_id],
             name: "memberships_unique_membership_index"
           )

    alter table(:accounts_users) do
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
      add :role, :text, null: false, default: "customer"

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "accounts_users_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:accounts_users, [:email], name: "accounts_users_unique_email_index")

    create table(:accounts_tokens, primary_key: false) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:accounts_api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :prefix, :text, null: false
      add :key_hash, :text, null: false
      add :scopes, :map, null: false, default: %{}
      add :last_used_at, :utc_datetime
      add :revoked_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:accounts_users,
            column: :id,
            name: "accounts_api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:accounts_api_keys, [:key_hash], name: "accounts_api_keys_key_hash_index")
  end

  def down do
    drop_if_exists unique_index(:accounts_api_keys, [:key_hash],
                     name: "accounts_api_keys_key_hash_index"
                   )

    drop constraint(:accounts_api_keys, "accounts_api_keys_user_id_fkey")

    drop table(:accounts_api_keys)

    drop table(:accounts_tokens)

    drop_if_exists unique_index(:accounts_users, [:email],
                     name: "accounts_users_unique_email_index"
                   )

    drop constraint(:accounts_users, "accounts_users_organization_id_fkey")

    alter table(:accounts_users) do
      remove :organization_id
      remove :role
      remove :hashed_password
      remove :email
    end

    drop_if_exists unique_index(:memberships, [:organization_id, :user_id],
                     name: "memberships_unique_membership_index"
                   )

    drop constraint(:memberships, "memberships_user_id_fkey")

    alter table(:memberships) do
      modify :user_id, :uuid
    end

    drop constraint(:organizations, "organizations_owner_id_fkey")

    alter table(:organizations) do
      modify :owner_id, :uuid
    end

    drop table(:accounts_users)

    drop_if_exists unique_index(:inventory_allergens, [:name],
                     name: "inventory_allergens_name_index"
                   )

    alter table(:inventory_allergens) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:inventory_material_allergen, "inventory_material_allergen_allergen_id_fkey")

    alter table(:inventory_material_allergen) do
      modify :allergen_id, :uuid
    end

    drop table(:inventory_allergens)

    drop constraint(:inventory_material_allergen, "inventory_material_allergen_material_id_fkey")

    drop table(:inventory_material_allergen)

    drop constraint(
           :inventory_material_nutritional_fact,
           "inventory_material_nutritional_fact_material_id_fkey"
         )

    drop constraint(
           :inventory_material_nutritional_fact,
           "inventory_material_nutritional_fact_nutritional_fact_id_fkey"
         )

    drop table(:inventory_material_nutritional_fact)

    drop_if_exists unique_index(:inventory_materials, [:sku],
                     name: "inventory_materials_sku_index"
                   )

    drop_if_exists unique_index(:inventory_materials, [:name],
                     name: "inventory_materials_name_index"
                   )

    drop table(:inventory_materials)

    drop_if_exists unique_index(:inventory_nutritional_facts, [:name],
                     name: "inventory_nutritional_facts_name_index"
                   )

    drop table(:inventory_nutritional_facts)

    drop constraint(:memberships, "memberships_organization_id_fkey")

    drop table(:memberships)

    alter table(:organizations) do
      remove :prefix
      remove :owner_id
      remove :plan
      remove :active
      remove :name
    end

    drop constraint(:settings, "settings_organization_id_fkey")

    alter table(:settings) do
      modify :organization_id, :uuid
    end

    drop table(:organizations)

    drop table(:settings)
  end
end
